# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_laravel_app
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_container
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./laravel_app:/var/www/html
    stdin_open: true
    tty: true